---
title: "Analiza danych"
output: html_document
---

# Opis danych
Do projektu wybrałem zbiór `iris`. Są to dane dotyczące wymiarów kwiatów irysa. 

Analizujemy 150 kwiatów podzielonych na trzy gatunki:
* Iris setosa,
* Iris versicolor,
* Iris virginica.

Mierzone cechy to długość i szerokość płatków oraz działek kielicha.

# Obliczenia i wykresy
Poniżej znajduje się kod, który przygotowuje dane (użyłem `dplyr`) i generuje trzy wykresy (`ggplot2`).

```{r}
library(dplyr)
library(ggplot2)

# 1. Przerabianie danych
moje_irysy <- iris %>%
  filter(Petal.Length > 1.4) %>%
  mutate(Stosunek_wymiarow = Petal.Length / Petal.Width) %>%
  group_by(Species) %>%
  summarise(
    Srednia_Dl = mean(Petal.Length),
    Srednia_Sz = mean(Petal.Width),
    Liczba_sztuk = n()
  )

# Wyświetlenie tabeli
knitr::kable(moje_irysy)

# 2. Wykres słupkowy - średnia długość płatka u irysów
ggplot(moje_irysy, aes(x = Species, y = Srednia_Dl, fill = Species)) +
  geom_col() +
  labs(title = "Średnia długość płatka irysa", x = "Gatunek", y = "Długość [cm]")

# 3. Wykres punktowy - wymiary działek kielicha
ggplot(iris, aes(x = Sepal.Length, y = Sepal.Width, color = Species)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Wymiary działek kielicha irysów", x = "Długość", y = "Szerokość")

# 4. Wykres pudełkowy - rozrzut długości płatków
ggplot(iris, aes(x = Species, y = Petal.Length, fill = Species)) +
  geom_boxplot() +
  labs(title = "Rozrzut wymiarów płatków irysów", x = "Gatunek", y = "Długość płatka")
